import { Event, Attendee, Analytics } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    name: 'Neon Dreams Festival',
    date: '2024-04-15',
    time: '21:00',
    location: 'Downtown Arena',
    category: 'Music',
    attendees: 1245,
    status: 'upcoming',
    image: '/event-1.jpg',
    description: 'Electronic music festival with top DJs',
    capacity: 2000,
  },
  {
    id: '2',
    name: 'Digital Art Expo',
    date: '2024-04-18',
    time: '14:00',
    location: 'Creative Hub',
    category: 'Art',
    attendees: 834,
    status: 'upcoming',
    image: '/event-2.jpg',
    description: 'Immersive digital art installations',
    capacity: 1500,
  },
  {
    id: '3',
    name: 'Web3 Summit',
    date: '2024-04-20',
    time: '10:00',
    location: 'Tech Center',
    category: 'Tech',
    attendees: 2156,
    status: 'ongoing',
    image: '/event-3.jpg',
    description: 'Blockchain and crypto conference',
    capacity: 3000,
  },
  {
    id: '4',
    name: 'Gaming Night Championship',
    date: '2024-04-22',
    time: '18:00',
    location: 'Gaming Arena',
    category: 'Gaming',
    attendees: 567,
    status: 'completed',
    image: '/event-4.jpg',
    description: 'Esports tournament with prizes',
    capacity: 1000,
  },
  {
    id: '5',
    name: 'Street Sports Fest',
    date: '2024-04-25',
    time: '16:00',
    location: 'Central Park',
    category: 'Sports',
    attendees: 1834,
    status: 'upcoming',
    image: '/event-5.jpg',
    description: 'Basketball, skateboarding, and more',
    capacity: 2500,
  },
  {
    id: '6',
    name: 'Lifestyle Brand Showcase',
    date: '2024-04-28',
    time: '19:00',
    location: 'Fashion District',
    category: 'Lifestyle',
    attendees: 612,
    status: 'upcoming',
    image: '/event-6.jpg',
    description: 'New collections from emerging brands',
    capacity: 1200,
  },
];

export const mockAttendees: Attendee[] = [
  {
    id: '1',
    name: 'Alex Chen',
    email: 'alex@example.com',
    joinedAt: '2024-03-15 10:30',
    status: 'checked-in',
  },
  {
    id: '2',
    name: 'Jordan Blake',
    email: 'jordan@example.com',
    joinedAt: '2024-03-15 11:45',
    status: 'registered',
  },
  {
    id: '3',
    name: 'Sam Rivera',
    email: 'sam@example.com',
    joinedAt: '2024-03-15 12:10',
    status: 'checked-in',
  },
  {
    id: '4',
    name: 'Taylor Moon',
    email: 'taylor@example.com',
    joinedAt: '2024-03-15 13:20',
    status: 'checked-in',
  },
  {
    id: '5',
    name: 'Casey Parker',
    email: 'casey@example.com',
    joinedAt: '2024-03-15 14:00',
    status: 'completed',
  },
];

export const mockAnalytics: Analytics = {
  totalAttendees: 8248,
  registrationRate: 87.5,
  checkInRate: 72.3,
  avgEngagement: 94.2,
  weeklyTrend: [
    { name: 'Mon', value: 1200, value2: 950 },
    { name: 'Tue', value: 1900, value2: 1350 },
    { name: 'Wed', value: 1600, value2: 1100 },
    { name: 'Thu', value: 2100, value2: 1600 },
    { name: 'Fri', value: 2800, value2: 2200 },
    { name: 'Sat', value: 2200, value2: 1800 },
    { name: 'Sun', value: 1400, value2: 950 },
  ],
  categoryBreakdown: [
    { name: 'Music', value: 28 },
    { name: 'Art', value: 18 },
    { name: 'Tech', value: 26 },
    { name: 'Gaming', value: 14 },
    { name: 'Sports', value: 10 },
    { name: 'Lifestyle', value: 4 },
  ],
  hourlyFlow: [
    { date: '9 AM', value: 120 },
    { date: '10 AM', value: 280 },
    { date: '11 AM', value: 450 },
    { date: '12 PM', value: 620 },
    { date: '1 PM', value: 780 },
    { date: '2 PM', value: 890 },
    { date: '3 PM', value: 920 },
    { date: '4 PM', value: 850 },
    { date: '5 PM', value: 700 },
  ],
  demographics: [
    { name: '18-24', value: 35 },
    { name: '25-34', value: 42 },
    { name: '35-44', value: 16 },
    { name: '45+', value: 7 },
  ],
};
